apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: reviews
  namespace: bookinfo
spec:
  template:
    spec:
      containers:
      - image: ochorny/reviews
        ports:
        - containerPort: 8080
        env:
          - name: SERVICES_DOMAIN # The environment variable printed out by the sample app
            value: "bookinfo.svc.cluster.local"
