name: Istio Install
on: [push]
jobs:
  istio:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python v3.
      uses: actions/setup-python@v1 
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: VKS context 
      uses: ventus-ag/vks-action@master
      with: 
        authUrl: ${{ secrets.URL }}
        projectName: ${{ secrets.PROJECT }}
        projectDomainName: ${{ secrets.DOMAIN }}
        userName: ${{ secrets.USER }}
        userDomainName: ${{ secrets.USERDOMAIN }}
        userPassword: ${{ secrets.PASSWORD }}
        clusterName: ${{ secrets.CLUSTER }}
    - name: Create istio-system Namespace
      run: |
        kubectl create namespace istio-system --dry-run -o yaml | kubectl apply -f -
    - name: Istio Init
      run: |
        git clone --branch '1.2.5' https://github.com/istio/istio.git && helm template istio/install/kubernetes/helm/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
    - name: Istio Demo Install
      run: |
        helm template istio/install/kubernetes/helm/istio --name istio --namespace istio-system --values istio/install/kubernetes/helm/istio/values-istio-demo.yaml | kubectl apply -f -
    - name: Bookinfo Install
      run: |
        kubectl label namespace default istio-injection=enabled && kubectl apply -f istio/samples/bookinfo/platform/kube/bookinfo.yaml && kubectl apply -f istio/samples/bookinfo/networking/bookinfo-gateway.yaml


    
